name       : perl-module-implementation
version    : 0.09
release    : 5
source     :
    - http://search.cpan.org/CPAN/authors/id/D/DR/DROLSKY/Module-Implementation-0.09.tar.gz : c15f1a12f0c2130c9efff3c2e1afe5887b08ccd033bd132186d1e7d5087fd66d
license    : Artistic-2.0
component  : programming.perl
summary    : This module abstracts out the process of choosing one of several underlying
    implementations for a module
description: |
    This module abstracts out the process of choosing one of several underlying implementations for a module
rundeps    :
    - perl-module-runtime
    - perl-try-tiny
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
